#import "@preview/barcala:0.2.0": apendice, informe, nomenclatura
#import "@preview/lilaq:0.5.0" as lq // Paquete para gráficos, puede ser omitido
#import "@preview/physica:0.9.6": * // Paquete para matemática y física, puede ser omitido
#import "@preview/zero:0.5.0" // Paquete para números lindos y unidades de medida, puede ser omitido

#show: informe.with(
  unidad-academica: "ingeniería",
  asignatura: "",
  trabajo: "ADVANCED METHODS OF MONITORING AND DESIGN OF SYSTEMS",
  equipo: "Group 22",
  autores: (
    (
      nombre: "Abdelrahman , Elsharkawy",
      email: "s8220949@studenti.unige.it",
      legajo: "S8220949",
      
    ),
    (
      nombre: "Abbas, alloul",
      email: "s4712172@studenti.unige.it",
      legajo: "S4712172",
    ),
    (
      nombre: "Eman , Sadig",
      email: "s6864398@studenti.unige.it",
      legajo: "S6864398",
    ),
  ),

  titulo: [Assignment #1 on Uncertainty Quantification
Monte Carlo simulation and MSPE Analysis
],
  // resumen: [*_Objetivo_ --- determinación de las constantes de tiempo ($tau$) de carga y descarga de un circuito RC. Análisis de la dependencia de $tau$ en función de los valores de resistencia y capacidad que conforman el circuito.*],


)

// Configuración de `zero`
#import zero: num, zi
#zero.set-num(
  decimal-separator: ",",
)
#zero.set-group(
  size: 3,
  separator: ".",
  threshold: (integer: 5, fractional: calc.inf),
)
#zero.set-unit(
  fraction: "inline",
)

// Bloques de matemática con números para citar
#set math.equation(numbering: "(1)")

// Unidades
#let Vm = zi.declare("V/m")


= Introduction
The main objective of this assignment is to estimate the electric power that can be generated by
installing a wind turbine.
The power generated P [W] is computed with the following equation


$
  P=c#sub("p") . 1/2 rho A v^3
$ <power-eq>

*where :*
-  c#sub("p") is the coefficient of performance [-]
- $rho$ is the air density [kg/m3]
- A is the area swept by the turbine rotor blades [m2]
- $v$ is the wind velocity [m/s]




= Tasks

== Evaluate mean μv and standard deviation σv of the wind velocity v and plot the corresponding PDF.
- After reading the wind velocity in 2025 from the excel sheet site C V[m/s]

- Using MATLAB’s Distribution Fitter App to evaluate mean μv and standard deviation σv of the wind velocity v and plot the corresponding PDF in @wind-pdf-fits

- From these parameters, MATLAB computes the mean and standard deviation as:
  - Mean μv = 7.7179 m/s
  - Standard deviation σv = 2.8461 m/s

#figure(
   image("wind_velocity_PDF_Fits.png"),
  caption: [wind velocity PDF with Fits],
)<wind-pdf-fits>

== The wind-speed data measured at were analyzed to determine which theoretical probability density function (PDF) best represents the empirical distribution.
#linebreak()
 Three distributions were tested using MATLAB’s Distribution Fitter App: Normal, Gamma, and Weibull.

#grid(
  columns: (1fr, 1fr, 1fr),
  // rows: (auto, 60pt),
  inset: 5pt,
  fill: (none ,none ,rgb("#8ae1ed50")),
  gutter: 3pt,
  [1. *The Normal distribution was fitted to the wind-speed data.*

-  Estimated parameters are:
  - Log likelihood:  -25523.3
  - $mu$:7.71794
  - $sigma^2$:8.10007],
  [2. *The Weibull distribution was fitted to the wind-speed data.*

-  Estimated parameters are:
  - Log likelihood:-25364.4
  - Shape A:8.66006
  - Scale B:2.89482 ],
  [3. *The Gamma distribution was fitted to the wind-speed data.*
-  Estimated parameters are:
  - $mu$:7.71794 , $sigma^2$:8.32244
  - Log likelihood:  -25164.6 
  - Shape A:7.15735 
  - Scale B:1.07832],
  
  
)


#text(weight:"bold")[Comparison of All Three Fits]

The Normal distribution does not represent the data well because it allows negative speeds and is symmetric. 
The Gamma distribution has the highest Log likelihood (closest to zero) at -25164.6.
Therefore, the Gamma distribution is the best fit for your data among the three tested distributions (Normal, Weibull, and Gamma). It most accurately models the underlying data structure. This reinforces the idea that your data is positive-only and likely positively skewed, as is typical for Gamma-distributed data.
Therefore, the #text(fill: blue)[*Gamma*] model was selected as the best representation of the wind-speed distribution at Site C.

== Running MonteCarlo (MC) simulations to estimate the electric power P generated by the wind turbine

Monte Carlo (MC) simulations were performed to estimate the turbine’s electric power output using random wind-speed values generated from the best PDF fit the Gamma distribution selected in *#2.2*
With three different numbers of samples (10, 10^3, 10^5). To generate random values of v,  For each run of MC, compute the power mean μP and standard deviation σP, and plot the corresponding PDFs. 


#figure(
   image("power pdf 10.png",width: 60%),
  caption: [PDF for 10 no. of samples],
)<ll>

- *For N = 10*
  -	Only 10 random wind speeds → small sample → very noisy result.
  -	The power mean varies more randomly and wildely.
  -	The runtime is very fast (0.002 s).
  -	This run is not reliable — too few samples.


#figure(
   image("power pdf 10e3.png",width: 60%),
  caption: [PDF for 10e3 no. of samples],
)
 - *For N = 1 000*
  -	Now you have enough samples to represent the Gamma wind-speed distribution properly.
  -	The mean stabilize bettween [12.1 - 13.2]kW.
  -	The histogram looks relatively smooth — the random variability “averages out.”
  -	The runtime is  fast (0.01 s).
This is a more stable, accurate result.

#figure(
   image("power pdf 10e5.png",width: 60%),
  caption: [PDF for 10e5 no. of samples],
)
- *For N = 100 000*
  - more samples, but the mean barely changes from [13.2]kW.
  -	The standard deviation also stays about the same.
  -	Runtime increases  to (0.9 s), but accuracy doesn’t improve much.
 So, increasing N further gives no real benefit — only slower computation.

#text(14pt)[
*after reviewing power pdfs with different samples and analyzing the results to determine which number of samples is the optimal for the MC simulation we chose using #text(fill: blue)[10e3] samples. As it is an accurate approximation of the power with minimal computational time.*]




==  fitting the PDF of power P with 3 different distribution functions.
Considering only the  number of samples determined in *#2.3* (N = 1000), fit the corresponding PDF of power P with at least 3 different distribution functions. 
when experimenting and trying different fits we execluded normal funciton as the power pdf is not symmetric and it wasn't an appropriate fit.
The Normal distribution gives a balanced shape but predicts negative power values, which are not realistic because a turbine cannot produce negative power.
Three distributions were tested using MATLAB’s Distribution Fitter App: burr, Gamma, and Weibull.



#figure(
   image("power_PDF_Fits.png"),
  caption: [power PDF with 3 Fits],
)

#figure(
   image("power_PDF_burr_fit.png"),
  caption: [power PDF with burr Fit],
)




#grid(
  columns: (1fr, 1fr, 1fr),
  // rows: (auto, 60pt),
  inset: 5pt,
  fill: (rgb("#8ae1ed50"),none,none),
  gutter: 3pt,
  [1. *The Burr distribution was fitted to the power data.*

-  Estimated parameters are:
  - Log likelihood:  -3580.52
  - $mu$:13.98 [kW]
  - $sigma^2$:592.53 [$k.W^2$]
  - $alpha$:17.4256 
  - $c$:1.22907   
  - $k$:2.10257
  ]
  
  ,
  [2. *The Weibull distribution was fitted to the power data.*

-  Estimated parameters are:
  - Log likelihood:-3603.23
  - $mu$:13.52
  - $sigma^2$:210.308
  - Shape A:13.094
  - Scale B:0.932967 ],
  [3. *The Gamma distribution was fitted to the power data.*
-  Estimated parameters are:
  
  - Log likelihood:   -3607.09
  - Shape A: 0.955786 
  - Scale B: 14.1964],
  
  
)

*  To compare the fitted models, both their statistical results and physical meaning were considered. Burr model fit is the one that better approximates the power PDF distribution.as the most realistic and reliable way to represent the variation in turbine power.*




== Estimate the power P generated by the wind turbine, perform a mean square pure error (MSPE) analysis referring to the MC simulations carried out in *#2.3* to  


#figure(
   image("MSPE.png"),
  caption: [mspe analysis],
)








the goal of this analysis is to verify whether the number of Monte Carlo samples selected in *#2.3* (N = 1000) provides an accurate and stable estimate of the mean turbine power output.
An MSPE analysis was performed using the Excel sheet MSPE ,Four independent Monte Carlo simulation runs were carried out for N = 100000.
For each run, the mean turbine power was computed and compared with the reference mean power. The MSPE was then calculated as the average of the squared differences between the estimated and reference means. this analysis quantifies how the sampling size affects the precision of the Monte Carlo estimate.



The MSPE decreases sharply when increasing the sample size from 10 to 1000 but it still fluctuates quite a bit, beyond around N=2700 the estimate of the mspe mean and std turbine power becomes much more stable and accurate.The results confirm that the random variations between repeated Monte Carlo runs become negligible when using around 2700 samples. This demonstrates that the selected sample size is statistically sufficient and computationally efficient.
nevertheless, going to N=100000 samples is unneccesary as mspe stabilizes in far less sample size,



